version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - dynamodb-local-network
networks:
  dynamodb-local-network:
